name: Deploy to Production

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read
  actions: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy_backend:
    name: Deploy | Backend
    uses: ./.github/workflows/workflow-deploy-backend.yaml
    secrets:
      GITHUB_TOKEN_ORG: ${{ secrets.PAT_TOKEN }}
    with:
      account: "730335381248"
      region: ap-northeast-1
